### ISSUE TITLE
After few selections of units with rect drag program crash on SetString

### ISSUE THREAD

**Issue by Jergar92** [DeamonRealm/Age_of_Empires_II#15]
**Build:** 0.3(in progress)
**Type:** 
Code

**Severity:**
[X]Critical   
[ ]Major   
[ ]Minor   

**Priority:**
[X]Urgent  
[ ]High  
[ ]Normal  
[ ]Low  

**Steps to reproduce:**
Start the solution
Create the grid map (F5)
Create 50 Arbalest
With click and drag select some units
Do the last steps 10 times.

**Frequency:** 
1/1

**Screenshot(optional):**

**Comment by PereRifa** [comment]
Fixed
