### ISSUE TITLE
Selected unit dies crash

### ISSUE THREAD

**Issue by Yulna** [DeamonRealm/Age_of_Empires_II#20]
**Build:** v0.3

**Type:** Code

**Severity:**
[x]Critical   
[ ]Major   
[ ]Minor   

**Priority:**
[x]Urgent  
[ ]High  
[ ]Normal  
[ ]Low  

**Steps to reproduce:**
Select one unit
Make it attack another unit
Select the other unit
Wait until it dies

**Frequency:** 1/1

**Comment by PereRifa** [comment]
Fixed
