### ISSUE TITLE
fogg of war

### ISSUE THREAD

**Issue by SrPerso** [DeamonRealm/Age_of_Empires_II#39]
**Build:**
0.7

**Type:**
fogg

**Severity:**
[ ]Critical   
[ ]Major   
[ x]Minor   

**Priority:**
[ ]Urgent  
[ ]High  
[ x]Normal  
[ ]Low  

**Steps to reproduce:**

open the game
go to ingame scene
select some units
move them to a place with fogg of war

**Description**
the fogg of war is working slower than the units movement
**Frequency:**
hight

**Screenshot(optional):**

**Comment by Yulna** [comment]
Intentional, updating the Fog of war at the dame rate as the unir move is very expansiva
