### ISSUE TITLE
You lose for no reason

### ISSUE THREAD

**Issue by Sergio111** [DeamonRealm/Age_of_Empires_II#47]
**Build:**
v.0.7

**Type:**
Code?

**Severity:**
[ ]Critical   
[X ]Major   
[ ]Minor   

**Priority:**
[ ]Urgent  
[X ]High  
[ ]Normal  
[ ]Low  

**Steps to reproduce:**

Play the game, go very fast to kill the enemy. The enemey doesn't harm you but you lose anyway.

**Frequency:**

1 out of 3.

**Screenshot(optional):**

**Comment by Yulna** [comment]
Was not random, it was that when any town center was destroyed the lose message would pop up
