### ISSUE TITLE
Game Crashing Bug

### ISSUE THREAD

**Issue by Jordior97** [DeamonRealm/Age_of_Empires_II#54]
**Build:**
v0.8

**Type:**
Game Crash

**Brief Description:**
He jugat 2 partides sense sortir del joc (fent Quit i després Play).
Estava passejant amb 3 soldats per una zona desconeguda.
He clickat per avançar i ha crashejat.

**Severity:**
[ x]Critical   
[ ]Major   
[ ]Minor   

**Priority:**
[ x]Urgent  
[ ]High  
[ ]Normal  
[ ]Low  

**Steps to reproduce:**
Jugar 2 partides seguides i caminar amb les tropes d'atac.

**Frequency:**
Ho he experimentat un cop

**Screenshot(optional):**
![captura](https://cloud.githubusercontent.com/assets/17125607/25988330/dd7a55b8-36f7-11e7-8024-1e2712dcf541.PNG)

**Comment by Yulna** [comment]
Needs help in being reproduced
